//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENIDO_SECUNDARIO
    {
        public decimal IdContenidoSecundario { get; set; }
        public string Url { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> UsuarioCreacion { get; set; }
        public Nullable<decimal> UsuarioModificacion { get; set; }
    }
}
