//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        public decimal IdNoticia { get; set; }
        public string Titular { get; set; }
        public string Bajada { get; set; }
        public string Cuerpo { get; set; }
        public string Imagen { get; set; }
        public Nullable<byte> Destacada { get; set; }
        public Nullable<decimal> Orden { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> UsuarioCreacion { get; set; }
        public Nullable<decimal> UsuarioModificacion { get; set; }
    }
}
