//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO_OBJETO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERMISO_OBJETO()
        {
            this.PERMISO = new HashSet<PERMISO>();
        }
    
        public decimal IdPermisoObjeto { get; set; }
        public Nullable<decimal> IdPermisoObjetoPadre { get; set; }
        public string Objeto { get; set; }
        public Nullable<int> TipoObjeto { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> UsuarioCreacion { get; set; }
        public Nullable<decimal> UsuarioModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO> PERMISO { get; set; }
    }
}
