//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PERFIL
    {
        public decimal IdUsuarioPerfil { get; set; }
        public Nullable<decimal> IdUsuario { get; set; }
        public Nullable<decimal> IdPerfil { get; set; }
        public Nullable<byte> Activo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<decimal> UsuarioCreacion { get; set; }
        public Nullable<decimal> UsuarioModificacion { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
