//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalitoPorPrestacion
    {
        public int Id { get; set; }
        public int PrestacionId { get; set; }
        public int AnalitoId { get; set; }
    
        public virtual Analito Analito { get; set; }
        public virtual Prestacion Prestacion { get; set; }
    }
}
