//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSistema
    {
        public int Id { get; set; }
        public Nullable<int> SeccionId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int BitacoraTipoId { get; set; }
        public string Observacion { get; set; }
    
        public virtual BitacoraTipo BitacoraTipo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
