//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraExamenes
    {
        public int Id { get; set; }
        public int ExamenId { get; set; }
        public int MuestraId { get; set; }
        public int PrestacionId { get; set; }
        public int EstadoId { get; set; }
        public string Correlativo { get; set; }
        public Nullable<int> DespachoLaboratorioId { get; set; }
        public Nullable<int> DespachoRtmId { get; set; }
        public Nullable<int> DespachoClienteId { get; set; }
        public string Observacion { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Usuario Usuarios { get; set; }
        public virtual Examen Examenes { get; set; }
    }
}
