//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraResultadoAnalito
    {
        public int Id { get; set; }
        public int ResultadoAnalitoId { get; set; }
        public int ExamenId { get; set; }
        public int AnalitoId { get; set; }
        public int MetodoId { get; set; }
        public int LimiteCuantificacionId { get; set; }
        public int NormaId { get; set; }
        public int LimiteMaximoPermitidoId { get; set; }
        public int LimiteDeteccionId { get; set; }
        public int UnidadMedidaId { get; set; }
        public string Resultado { get; set; }
        public string Observacion { get; set; }
        public bool Informar { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ResultadoAnalito ResultadoAnalito { get; set; }
    }
}
