//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examen()
        {
            this.BitacoraExamenes = new HashSet<BitacoraExamenes>();
            this.Rechazos = new HashSet<Rechazo>();
            this.ResultadosAnalitos = new HashSet<ResultadoAnalito>();
        }
    
        public int Id { get; set; }
        public int MuestraId { get; set; }
        public int PrestacionId { get; set; }
        public int EstadoId { get; set; }
        public string Correlativo { get; set; }
        public Nullable<int> DespachoLaboratorioId { get; set; }
        public Nullable<int> DespachoRtmId { get; set; }
        public Nullable<int> DespachoClienteId { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraExamenes> BitacoraExamenes { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Muestra Muestra { get; set; }
        public virtual Prestacion Prestacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechazo> Rechazos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoAnalito> ResultadosAnalitos { get; set; }
    }
}
