//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionalidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionalidad()
        {
            this.Funcionalidades = new HashSet<Funcionalidad>();
            this.FuncionalidadesPorRol = new HashSet<FuncionalidadPorRol>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public string NombreIcono { get; set; }
        public int Orden { get; set; }
        public bool Visible { get; set; }
        public int SistemaId { get; set; }
        public Nullable<int> FuncionalidadPadreId { get; set; }
        public bool ALaDerecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionalidad> Funcionalidades { get; set; }
        public virtual Funcionalidad FuncionalidadPadre { get; set; }
        public virtual Sistema Sistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncionalidadPorRol> FuncionalidadesPorRol { get; set; }
    }
}
