//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratorioEntities : DbContext
    {
        public LaboratorioEntities()
            : base("name=LaboratorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambiente> Ambientes { get; set; }
        public virtual DbSet<Sistema> Sistemas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuarioPorSistema> UsuariosPorSistema { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Laboratorio> Laboratorios { get; set; }
        public virtual DbSet<Prestacion> Prestaciones { get; set; }
        public virtual DbSet<Region> Regiones { get; set; }
        public virtual DbSet<Subdepartamento> Subdepartamentos { get; set; }
        public virtual DbSet<Comuna> Comunas { get; set; }
        public virtual DbSet<DireccionesDespacho> DireccionesDespachos { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Muestra> Muestras { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Solicitud> Solicitudes { get; set; }
        public virtual DbSet<TipoMuestraPorPrestacion> TiposMuestraPorPrestaciones { get; set; }
        public virtual DbSet<TipoRetiro> TiposRetiros { get; set; }
        public virtual DbSet<UsuarioPorLaboratorio> UsuariosPorLaboratorios { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
        public virtual DbSet<BitacoraExamenes> BitacoraExamenes { get; set; }
        public virtual DbSet<Examen> Examenes { get; set; }
        public virtual DbSet<Funcionalidad> Funcionalidades { get; set; }
        public virtual DbSet<FuncionalidadPorRol> FuncionalidadesPorRol { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<MotivoRechazo> MotivosRechazo { get; set; }
        public virtual DbSet<MotivoRechazoPorLaboratorio> MotivosRechazoPorLaboratorios { get; set; }
        public virtual DbSet<Rechazo> Rechazos { get; set; }
        public virtual DbSet<Seccion> Secciones { get; set; }
        public virtual DbSet<Procedencia> Procedencias { get; set; }
        public virtual DbSet<Feriado> Feriados { get; set; }
        public virtual DbSet<TipoObservacion> TiposObservaciones { get; set; }
        public virtual DbSet<MuestraObservacion> MuestraObservaciones { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Analito> Analitos { get; set; }
        public virtual DbSet<AnalitoPorPrestacion> AnalitosPorPrestaciones { get; set; }
        public virtual DbSet<Metodo> Metodos { get; set; }
        public virtual DbSet<MetodoPorAnalito> MetodosPorAnalitos { get; set; }
        public virtual DbSet<TipoMuestra> TiposMuestras { get; set; }
        public virtual DbSet<LimiteMaximoPermitido> LimitesMaximosPermitidos { get; set; }
        public virtual DbSet<Norma> Normas { get; set; }
        public virtual DbSet<ResultadoAnalito> ResultadosAnalitos { get; set; }
        public virtual DbSet<UnidadMedida> UnidadesMedidas { get; set; }
        public virtual DbSet<LimiteDeteccion> LimitesDeteccion { get; set; }
        public virtual DbSet<EstadoIncidente> EstadosIncidentes { get; set; }
        public virtual DbSet<BitacoraSistema> BitacoraSistemas { get; set; }
        public virtual DbSet<BitacoraTipo> BitacoraTipos { get; set; }
        public virtual DbSet<BitacoraResultadoAnalito> BitacoraResultadosAnalitos { get; set; }
        public virtual DbSet<LimiteCuantificacion> LimitesCuantificaciones { get; set; }
    }
}
