//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laboratorio()
        {
            this.Prestaciones = new HashSet<Prestacion>();
            this.UsuariosPorLaboratorios = new HashSet<UsuarioPorLaboratorio>();
            this.MotivosRechazoPorLaboratorios = new HashSet<MotivoRechazoPorLaboratorio>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Fono { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
        public int SeccionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestacion> Prestaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioPorLaboratorio> UsuariosPorLaboratorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotivoRechazoPorLaboratorio> MotivosRechazoPorLaboratorios { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
