//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muestra()
        {
            this.Examenes = new HashSet<Examen>();
            this.MuestraObservaciones = new HashSet<MuestraObservacion>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string LugarToma { get; set; }
        public string Lote { get; set; }
        public string Encargado { get; set; }
        public string Observacion { get; set; }
        public int TipoMuestraId { get; set; }
        public Nullable<int> PacienteId { get; set; }
        public int SolicitudId { get; set; }
        public int TipoRetiroId { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual TipoRetiro TipoRetiro { get; set; }
        public virtual Paciente Pacientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen> Examenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuestraObservacion> MuestraObservaciones { get; set; }
        public virtual TipoMuestra TipoMuestra { get; set; }
    }
}
