//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestacion()
        {
            this.TiposMuestraPorPrestaciones = new HashSet<TipoMuestraPorPrestacion>();
            this.Examenes = new HashSet<Examen>();
            this.AnalitosPorPrestaciones = new HashSet<AnalitoPorPrestacion>();
        }
    
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public int LaboratorioId { get; set; }
        public Nullable<int> DiaMinimo { get; set; }
        public Nullable<int> DiaMaximo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Laboratorio Laboratorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoMuestraPorPrestacion> TiposMuestraPorPrestaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen> Examenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalitoPorPrestacion> AnalitosPorPrestaciones { get; set; }
    }
}
