//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultadoAnalito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResultadoAnalito()
        {
            this.BitacoraResultadoAnalitos = new HashSet<BitacoraResultadoAnalito>();
        }
    
        public int Id { get; set; }
        public int ExamenId { get; set; }
        public int AnalitoId { get; set; }
        public int MetodoId { get; set; }
        public int LimiteCuantificacionId { get; set; }
        public int NormaId { get; set; }
        public int LimiteMaximoPermitidoId { get; set; }
        public int LimiteDeteccionId { get; set; }
        public int UnidadMedidaId { get; set; }
        public string Resultado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public bool Informar { get; set; }
    
        public virtual Analito Analito { get; set; }
        public virtual Examen Examen { get; set; }
        public virtual LimiteMaximoPermitido LimiteMaximoPermitido { get; set; }
        public virtual Metodo Metodo { get; set; }
        public virtual Norma Norma { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual LimiteDeteccion LimiteDeteccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraResultadoAnalito> BitacoraResultadoAnalitos { get; set; }
        public virtual LimiteCuantificacion LimiteCuantificacion { get; set; }
    }
}
