//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Muestras = new HashSet<Muestra>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> NumeroFormulario { get; set; }
        public int NumeroComercializacion { get; set; }
        public string ProfesionalSolicitante { get; set; }
        public string ServicioSolicitante { get; set; }
        public int DireccionDespachoId { get; set; }
        public int ProcedenciaId { get; set; }
    
        public virtual DireccionesDespacho DireccionesDespacho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muestra> Muestras { get; set; }
        public virtual Procedencia Procedencia { get; set; }
    }
}
