//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidades
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public string Codigo { get; set; }
        public int ContactoCodigo { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int ComunaId { get; set; }
    
        public virtual Comuna Comuna { get; set; }
        public virtual Sucursales Sucursal { get; set; }
    }
}
