//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isp.Laboratorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.UsuariosPorLaboratorios = new HashSet<UsuarioPorLaboratorio>();
            this.BitacoraExamenes = new HashSet<BitacoraExamenes>();
            this.Rechazos = new HashSet<Rechazo>();
            this.MuestraObservaciones = new HashSet<MuestraObservacion>();
            this.MuestraObservaciones1 = new HashSet<MuestraObservacion>();
            this.BitacoraSistemas = new HashSet<BitacoraSistema>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RUT { get; set; }
        public string CorreoElectronico { get; set; }
        public int RolId { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public bool Activo { get; set; }
        public string ContrasenaFEA { get; set; }
        public string ConfiguracionFEA { get; set; }
    
        public virtual UsuarioPorSistema UsuariosPorSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioPorLaboratorio> UsuariosPorLaboratorios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraExamenes> BitacoraExamenes { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechazo> Rechazos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuestraObservacion> MuestraObservaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuestraObservacion> MuestraObservaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraSistema> BitacoraSistemas { get; set; }
    }
}
