//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOficinaDOM.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SeccionResouces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeccionResouces() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebOficinaDOM.Resources.SeccionResouces", typeof(SeccionResouces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible crear más de {0} contenidos principales.
        /// </summary>
        internal static string CreateContenidoPrincipal_P1 {
            get {
                return ResourceManager.GetString("CreateContenidoPrincipal_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible dejar menos de {0} contenidos principales.
        /// </summary>
        internal static string DeleteContenidoPrincipal_P1 {
            get {
                return ResourceManager.GetString("DeleteContenidoPrincipal_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible dejar menos de {0} contenidos principales activos.
        /// </summary>
        internal static string DisableContenidoPrincipal_P1 {
            get {
                return ResourceManager.GetString("DisableContenidoPrincipal_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible habilitar más de {0} contenidos principales.
        /// </summary>
        internal static string EnableContenidoPrincipal_P1 {
            get {
                return ResourceManager.GetString("EnableContenidoPrincipal_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin dependencia.
        /// </summary>
        internal static string NoDepend_P0 {
            get {
                return ResourceManager.GetString("NoDepend_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no responde correctamente.
        /// </summary>
        internal static string NoResponseService_P0 {
            get {
                return ResourceManager.GetString("NoResponseService_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados de contenido.
        /// </summary>
        internal static string NoResultsContent_P0 {
            get {
                return ResourceManager.GetString("NoResultsContent_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados de logo.
        /// </summary>
        internal static string NoResultsLogo_P0 {
            get {
                return ResourceManager.GetString("NoResultsLogo_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione archivo para actualizar Logo.
        /// </summary>
        internal static string RequiredLogo_P0 {
            get {
                return ResourceManager.GetString("RequiredLogo_P0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No definido.
        /// </summary>
        internal static string Undefined_P0 {
            get {
                return ResourceManager.GetString("Undefined_P0", resourceCulture);
            }
        }
    }
}
