//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class domEntities : DbContext
    {
        public domEntities()
            : base("name=domEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditoria { get; set; }
        public virtual DbSet<Contenido_Logo> Contenido_Logo { get; set; }
        public virtual DbSet<Contenido_Principal> Contenido_Principal { get; set; }
        public virtual DbSet<Contenido_Secundario> Contenido_Secundario { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Noticia_Galeria> Noticia_Galeria { get; set; }
        public virtual DbSet<Organismo> Organismo { get; set; }
        public virtual DbSet<Organismo_Tipo> Organismo_Tipo { get; set; }
    
        public virtual ObjectResult<USP_MENU_Select_HomePage_Result> USP_MENU_Select_HomePage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_MENU_Select_HomePage_Result>("USP_MENU_Select_HomePage");
        }
    
        public virtual ObjectResult<USP_MENU_Select_Mantenedor_Result> USP_MENU_Select_Mantenedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_MENU_Select_Mantenedor_Result>("USP_MENU_Select_Mantenedor");
        }
    
        public virtual ObjectResult<USP_MENU_Select_Parent_Result> USP_MENU_Select_Parent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_MENU_Select_Parent_Result>("USP_MENU_Select_Parent");
        }
    
        public virtual ObjectResult<USP_ORGANISMO_Select_Filtro_Result> USP_ORGANISMO_Select_Filtro(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ORGANISMO_Select_Filtro_Result>("USP_ORGANISMO_Select_Filtro", nombreParameter);
        }
    }
}
