//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public decimal IdLog { get; set; }
        public Nullable<int> TipoAuditoria { get; set; }
        public string Pagina { get; set; }
        public string Evento { get; set; }
        public string Clase { get; set; }
        public string Cabecera { get; set; }
        public string Mensaje { get; set; }
        public string Ip { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario { get; set; }
    }
}
