//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia_Galeria
    {
        public decimal IdNoticiaGaleria { get; set; }
        public Nullable<decimal> IdNoticia { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Noticia Noticia { get; set; }
    }
}
