//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiDom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organismo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organismo()
        {
            this.Organismo1 = new HashSet<Organismo>();
        }
    
        public decimal IdOrganismo { get; set; }
        public Nullable<decimal> IdOrganismoTipo { get; set; }
        public Nullable<decimal> IdOrganismoPadre { get; set; }
        public string CodigoComuna { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Icono { get; set; }
        public string Logo { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organismo> Organismo1 { get; set; }
        public virtual Organismo Organismo2 { get; set; }
        public virtual Organismo_Tipo Organismo_Tipo { get; set; }
    }
}
